// <auto-generated />
namespace Proj_EF_Agenda.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NumbersAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumbersAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202210110119556_NumbersAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
